INSERT INTO HRHSSCHEMA.CandidateStatus (STATUS) VALUES ('Pending');
INSERT INTO HRHSSCHEMA.CandidateStatus (STATUS) VALUES ('Passed');
INSERT INTO HRHSSCHEMA.CandidateStatus (STATUS) VALUES ('Archived');

