INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Software Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Software Support Engineer');
INSERT INTO HRHSSCHEMA.positions(name) VALUES ('Staff Software Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Staff Software Support Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Senior Staff Software Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Business Analyst');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Associate Project Manager');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Presales Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Project Manager');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('HR Associate');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Associate Software Test Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('HR Executive');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Software Test Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('HR Specialist');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Associate Software Support Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Marketing Executive');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Marketing Specialist');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Sales Account Manager');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Junior Accountant');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Senior Accountant');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('IT Admin');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Senior IT Admin');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Systems Engineer');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('HR Intern');
INSERT INTO HRHSSCHEMA.positions (name) VALUES ('Software Intern');
