INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Irrelevant Experience');
INSERT INTO HRHSSCHEMA.reasonsOfFailure  (name) VALUES ('Out of The Country');
INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Interest');
INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Language');
INSERT INTO HRHSSCHEMA.reasonsOfFailure  (name) VALUES ('Culture');
INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Communication Skills');
INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Expected Salary');
INSERT INTO HRHSSCHEMA.reasonsOfFailure  (name) VALUES ('Overqualified');
INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Gender');
INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Age');
INSERT INTO HRHSSCHEMA.reasonsOfFailure  (name) VALUES ('Attitude');
INSERT INTO HRHSSCHEMA.reasonsOfFailure (name) VALUES ('Technical Competence');